name: Image Build

on:
  schedule:
    - cron: '0 0 * * *' # nightly
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - development
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    strategy:
      matrix:
        platform: ["amd64", "arm64"]
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package version
        id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/recommendarr
            ghcr.io/${{ github.repository_owner }}/recommendarr
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern={{major}}
            type=schedule,pattern={{raw}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/${{ matrix.platform }}
          cache-from: |
            ${{ format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2}-{3},mode=max', github.repository_owner, matrix.platform, steps.package_version.outputs.VERSION) }}
          cache-to: |
            ${{ format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2}-{3}', github.repository_owner, matrix.platform, steps.package_version.outputs.VERSION) || '' }}
        if: |
          github.event_name == 'push' && (
            github.ref == 'refs/heads/development' ||
            startsWith(github.ref, 'refs/tags/v') ||
            github.event_name == 'pull_request')

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.builder.outputs.OUTPUT_FILE }}
          path: ${{ steps.builder.outputs.OUTPUT_FILE }}
